### ISSUE TITLE
gorm v2.0 Adaptation

### ISSUE THREAD

**Issue by YLLL-ux** [t-tiger/gorm-bulk-insert#56] opened 2023-10-23 08:08 UTC
gormbulk.BulkInsert(db, sliceValue, 3000)  can't use "gorm.io/gorm" db ???

**Comment by bombsimon** [comment] 2023-10-23 08:50
Duplicate of #49 and #54. Gorm v2 already supports bulk actions so no need for this package to work with Gorm v2.

**Closed as completed by bombsimon** 2023-10-23 08:50 UTC
