### ISSUE TITLE
Auto Increment of ID doesn't work with batch insert

### ISSUE THREAD

**Issue by mannu2612** [t-tiger/gorm-bulk-insert#14] opened 2019-10-23 06:39 UTC
I have an auto increment ID field defined in a struct like this:

```
type MasterJob struct {
	MasterJobID int       `gorm:"column:master_job_id;not null;AUTO_INCREMENT"`
	StartedAt   time.Time `gorm:"column:started_at;not null"`
	CompletedAt time.Time `gorm:"column:completed_at;"`
	Status      Status    `gorm:"column:status;"`
}
```

When I try to do a batch insert, I get an error 

> pq: duplicate key value violates unique constraint "master_jobs_pkey"

Following is my code that uses gorm-bulk-insert and throws an error:

```
masterJob := &models.MasterJob{
		Status:    models.StatusInprogress,
		StartedAt: time.Now(),
	}

	masterJobs := make([]*models.MasterJob, 0)
	masterJobs = append(masterJobs, masterJob)
	masterJob = &models.MasterJob{
		Status:    models.StatusInprogress,
		StartedAt: time.Now(),
	}
	masterJobs = append(masterJobs, masterJob)

	y := make([]interface{}, len(masterJobs))
	for i, v := range masterJobs {
		y[i] = *v
	}
	err := gormbulk.BulkInsert(r.DB, y, 3000)
	if err != nil {
		fmt.Println(err)
	}
```

**Comment by bombsimon** [comment] 2019-11-21 09:02
Did you create the table with `gorm` migrations? What does the `master_jobs_pkey` look like? I cannot seem to reproduce this. 🤔 

This is how I create my table:

```sh
CREATE TABLE my_types ( id SERIAL NOT NULL UNIQUE, value VARCHAR (20) );
```

Resulting in

```sh
\d+ my_types
                                                       Table "public.my_types"
 Column |         Type          | Collation | Nullable |               Default                | Storage  | Stats target | Description
--------+-----------------------+-----------+----------+--------------------------------------+----------+--------------+-------------
 id     | integer               |           | not null | nextval('my_types_id_seq'::regclass) | plain    |              |
 value  | character varying(20) |           |          |                                      | extended |              |
Indexes:
    "my_types_id_key" UNIQUE CONSTRAINT, btree (id)
Access method: heap
```

Then I run this code. Sorry to re-create your example but this code is complete and copy-pasteable.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	gormbulk "github.com/t-tiger/gorm-bulk-insert"
)

type MyType struct {
	ID    int `gorm:"AUTO_INCREMENT"`
	Value string
}

func main() {
	db, err := gorm.Open(
		"postgres",
		"host=localhost port=5432 user=postgres dbname=test password=pass sslmode=disable",
	)

	if err != nil {
		panic(err)
	}

	defer db.Close()

	toInsert := []interface{}{
		MyType{Value: "first"},
		MyType{Value: "second"},
		MyType{Value: "third"},
	}

	if err := gormbulk.BulkInsert(db, toInsert, 3000); err != nil {
		panic(err)
	}
}
```

After I run the code the first time:

```sh
SELECT * FROM my_types;
 id | value
----+--------
  1 | first
  2 | second
  3 | third
(3 rows)
```

And the second time

```sh
SELECT * FROM my_types;
 id | value
----+--------
  1 | first
  2 | second
  3 | third
  4 | first
  5 | second
  6 | third
(6 rows)
```

For details, this is how I run my postgres instance.

```sh
docker run -it --rm -p 5432:5432  -e POSTGRES_PASSWORD=pass postgres
```

**Comment by t-tiger** [comment] 2019-11-24 02:47
@mannu2612
Sorry for late response🙏. Certainly there was a mistake in the program. It is fixed by below commit. Thanks to this issue, I can notice.
77b6f925eea00a284f4a98fc5d029a7903339e7f

In the previous program, if the name of auto_increment field is not `ID`, this field will be targeted for insertion. Since it was solved by the above commit, I'll close this issue.

**Closed as completed** 2019-11-24 02:47 UTC
